services:

  web:
    build: ./app
    container_name: java-app
    ports:
      - "9595:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    labels:
      project: "day34-task"
      service: "web"

  mysql:
    image: mysql: latest
    
    container_name: mysql-db
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    
    networks:
      - app-network
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-cache
    
    networks:
      - app-network
      
    labels:
      project: "day34-task"
      service: "cache"

networks:
  app-network:

volumes:
  mysql-data:
