services:

  web:
    build: ./app
    container_name: java-app
    ports:
      - "9595:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    labels:
      - "tier=frontend"

  mysql:
    image: mysql:8.0
    
    container_name: mysql-db
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb

    ports:
    - "3306:3306"
      
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    
    networks:
      - app-network

      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

    labels:
      - "tier=backend"  


  redis:
    image: redis:7
    container_name: redis-cache

    ports:
    - "6379:6379"
    
    networks:
      - app-network
      
    labels:
      - "tier=cache"

networks:
  app-network:

volumes:
  mysql-data:
