apiVersion: v1
kind: Pod
metadata:
  name: live-config-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["sh", "-c", "while true; do cat /etc/config/message; sleep 5; done"]
      volumeMounts:
        - name: live-config-volume
          mountPath: /etc/config
  volumes:
    - name: live-config-volume
      configMap:
        name: live-config
